Bugfix: passing the HTTP response's body to REXML instead of the entire HTTP response.
Fixes the following error:
  RuntimeError: Net::HTTPCreated is not a valid input stream.  It must walk like either a String, an IO, or a Source.